# Generated by Django 4.2.9 on 2024-02-15 13:54
import csv
from uuid import UUID

from django.db import migrations, IntegrityError

CATEGORIES = [
    "movies",
    "music",
    "hobbies",
    "children",
    "home",
    "humor",
    "useful",
    "psychology",
    "education",
    "education",
    "education",
    "languages",
    "work",
    "travel",
]


def fill_categories(apps, schema_editor):
    Category = apps.get_model("playlists", "Category")
    for name in CATEGORIES:
        try:
            Category.objects.create(name=name)
        except (IntegrityError, AttributeError):
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0006_path_category_image"),
    ]

    operations = [
        migrations.RunPython(fill_categories, migrations.RunPython.noop),
    ]
